#!/bin/bash
# preinst script for calm-catcalc
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    install|upgrade)
        echo ""
        echo "Před instalací si prosím přečtěte naše licenční podmínky dané licencí GNU GPL3."
        echo "Licence:"
        echo "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
        Upstream-Name: calmcatcalc
        Upstream-Contact: Pavel Hyza <xhyzapa00@vutbr.cz>

        Files: *
        Copyright: 2024 Jan Kalina <xkalinj00@vutbr.cz>
                2024 David Krejci <xkrejcd00@vutbr.cz>
                2024 Lukas Farkasovsky <xfarkal00@vutbr.cz>
                2024 Pavel Hyza <xhyzapa00@vutbr.cz>
        License: GPL-3.0+

        Files: debian/*
        Copyright: 2024 Pavel Hyza <xhyzapa00@vutbr.cz>
        License: GPL-3.0+

        License: GPL-3.0+
        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.
        .
        This package is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.
        .
        You should have received a copy of the GNU General Public License
        along with this program. If not, see <https://www.gnu.org/licenses/>.
        .
        On Debian systems, the complete text of the GNU General
        Public License version 3 can be found in \"/usr/share/common-licenses/GPL-3\"."
        echo "Souhlasíte s licenčními podmínkami? (Y/n)"
        read response
        if [[ "$response" =~ ^(yes|y|YES|Y)$ ]]; then
            echo "Uživatel souhlasil s licenčními podmínkami."
        else
            echo "Instalace byla zrušena uživatelem."
            exit 1
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0