#
# Tým:    Calm CatCalc Coder
#
# Autoři: Farkašovský Lukáš    <xfarkal00>
#         Hýža Pavel           <xhyzapa00>
#         Kalina Jan           <xkalinj00>
#         Krejčí David         <xkrejcd00>
#

# Cíl "hello" pro překlad a sestavení programu "hello"
hello: hello.Calm
	gcc -std=c11 hello.c -o hello