name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y make g++ lcov
    - name: Check for Makefile
      run: |
        if [ ! -f src/Makefile ]; then
          echo "Makefile not found, skipping build."
          exit 78
        fi
    - name: Build all
      run: make -C src
    - name: Test
      run: make -C src test
    - name: Clean build
      run: make -C src clean-build
